version: "3"

services:
    vk-bot-nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        networks:
            - internal
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./backend/:/vk-bot/
            - ./logs/nginx:/var/log/nginx/
    vk-bot-php:
        image: php:8.1-fpm-alpine
        env_file:
            - .env
            - db.env
        networks:
            - internal
        volumes:
            - ./backend/:/vk-bot/
            - ./logs/php.log:/var/log/fpm-php.www.log
    composer:
        build:
            dockerfile: ./Dockerfile
        networks:
            - internal
        volumes:
            - ./backend/:/vk-bot/
    db:
        image: postgres:15-alpine
        restart: always
        environment:
            - db.env
        ports:
            - "5432:5432"
networks:
    internal:
        driver: bridge
