version: "3"

services:
    nginx:
        image: nginx
        ports:
            - "8080:80"
        networks:
            - internal
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./backend/:/vk-bot/
            - ./logs/nginx:/var/log/nginx/
        depends_on:
            - php

    php:
        build:
            context: ./backend/
            dockerfile: Dockerfile
        env_file:
            - ./backend/.env
            - ./database/db.env
        expose:
            - 9000
        networks:
            - internal
        volumes:
            - ./backend/:/vk-bot/
            - ./logs/php.log:/var/log/fpm-php.www.log
        depends_on:
            - db

    db:
        build:
            context: ./database
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ./database/db.env
        ports:
            - "5432:5432"
        networks:
            - internal
        volumes:
            - ./database/:/vk-bot/

networks:
    internal:
        driver: bridge
